name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Make sure this version is up to date.

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3  # Ensure correct cache version.
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v3  # Use the latest version of upload-artifact.
        with:
          name: mic-to-speaker-apk
          path: app/build/outputs/apk/release/app-release.apk
